### ISSUE TITLE
Ability to configure the agent to be downloaded from a configurable url

### ISSUE THREAD

**Issue by manitheja1** [Dynatrace/libbuildpack-dynatrace#15]
Hi Team,

We tried using this hook module as part of non-java buildpacks(which already has this hook) in our enterprise. We noticed that the dynatrace oneagent installation failed as the buildpack can't download the agent successfully. 
This happened because the agent which the buildpack trying to download is residing outside the platform. Due to cyber and security reasons, its not allowed to download the files externally(outside the platform). 
We need a solution through  which agent can be downloaded from the source which can be configured as parameter something like download_url(oneagent_url) in vcapp?

**Comment by manitheja1** [comment]
Hi Team,
Closing the ticket as the corresponding changes are merged !!

Also wanted to know when will the changes will be added to release? This will help us to request cloudfoundary team to include this latest hook release in non java buildpacks.

Thanks,
Manitheja

**Comment by arthfl** [comment]
Resolved with #16
