### ISSUE TITLE
CF Buildpacks tests failing after latest libbuildpack-dynatrace release

### ISSUE THREAD

**Issue by brayanhenao** [Dynatrace/libbuildpack-dynatrace#21]
Some of our (CF Buildpacks) Buildpacks started to show errors in integration tests after the `libbuildpack-dynatrace` library was updated from `1.4.2` to `1.5.0`.

Was there a significant change in this release that causes the tests to fail? Something to do with fixtures, should they have any additional settings?

Buildpacks failing (On which `dependabot` has performed the update):
- [Python Buildpack](https://buildpacks.ci.cf-app.com/teams/main/pipelines/python-buildpack/jobs/specs-lts-integration-develop/builds/993#L62790886:229)
- [Go Buildpack](https://github.com/cloudfoundry/go-buildpack/runs/6351811368?check_suite_focus=true#step:5:412)
- [Staticfile Buildpack](https://buildpacks.ci.cf-app.com/teams/main/pipelines/staticfile-buildpack/jobs/specs-edge-integration-develop/builds/522#L62790d35:331)

Error message:

```bash
-----> Setting up Dynatrace OneAgent injection...
       DEBUG: Copy dynatrace-env.sh to /tmp/contents1126887780/deps/0/profile.d/dynatrace-env.sh
       DEBUG: Open /tmp/contents1126887780/deps/0/profile.d/dynatrace-env.sh for modification...
       DEBUG: Setting LD_PRELOAD...
       DEBUG: Setting DT_LOGSTREAM to stdout...
       DEBUG: Preparing custom properties...
       DEBUG: Fetching updated OneAgent configuration from tenant... 
       DEBUG: Successfully fetched OneAgent config from API
       **ERROR** Failure while reading OneAgent config file /tmp/app/dynatrace/oneagent/agent/conf/ruxitagentproc.conf: open /tmp/app/dynatrace/oneagent/agent/conf/ruxitagentproc.conf: no such file or directory
       **ERROR** Error during agent config update: open /tmp/app/dynatrace/oneagent/agent/conf/ruxitagentproc.conf: no such file or directory
       **ERROR** After Compile: open /tmp/app/dynatrace/oneagent/agent/conf/ruxitagentproc.conf: no such file or directory
```

**Comment by brayanhenao** [comment]
@arthfl Any update on this?

**Comment by arthfl** [comment]
@brayanhenao 
The integration tests in those buildpacks are missing a part in the fake API which is used there.
Currently in the process of preparing this for all go-based buildpacks we support.

**Comment by brayanhenao** [comment]
@arthfl Any estimate of how long these changes may take?

**Comment by brayanhenao** [comment]
Hi @arthfl, any update on this? `Dependabot` keeps updating `libbuildpack-dynatrace` to the latest version and now it's a little bit noisy for our Buildpacks repositories.

**Comment by arthfl** [comment]
Sorry, been quite busy.

I can remove the 1.5.0 version tag until i've prepared everything on my side for a proper integration test to save you folks some noise. Would that help as a temporary mitigation?

**Comment by arthfl** [comment]
@brayanhenao  i deleted the release for now.
That should you give you a bit more silence while i prepare everything :-)
